### ISSUE TITLE
[ModuleNotFoundError: No Module Named Selenium] error in line 8

### ISSUE THREAD

**Issue by NithyanthK** [crnprasanna/Instacart-delivery-slot-finder#1]
I have downloaded selenium server v3.141 (the version you have) and it still does not make a difference. I have already set up the settings.py file. I am running this thru command promt on windows 10 latest version.

**Comment by crnprasanna** [comment]
Hi ,
  Thanks for letting me know the issue,
May I know after you cloned repo, did you ran "pip3 install -r requirements.txt" ?
looks like you would have skipped.
