### ISSUE TITLE
Run time errorwith check delivery slot

### ISSUE THREAD

**Issue by narayana-konakalla** [crnprasanna/Instacart-delivery-slot-finder#2]
Err: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="header"]/div/div/div[4]/div[2]/div[2]/span/a/span"}
  (Session info: headless chrome=81.0.4044.92)

**Comment by narayana-konakalla** [comment]
[20200414.log](https://github.com/crnprasanna/Instacart-delivery-slot-finder/files/4478994/20200414.log)

**Comment by crnprasanna** [comment]
Handled runtime error, please do 'git pull' and rerun, thanks for lettting me know.
